export const MARKDOWN_SYNTAX = {
  "Heading 1": "# Insert text here",
  "Heading 2": "## Insert text here",
  "Heading 3": "### Insert text here",
  "Heading 4": "#### Insert text here",
  "Heading 5": "##### Insert text here",
  "Heading 6": "###### Insert text here",
  "Ordered List": "1. First Item \n 2. Second Item \n 3. Third Item",
  "Unordered List": "- First Item \n - Second Item \n - Third Item",
  Hyperlink: "[title](https://www.example.com)",
  Image: "![alt text](image.jpg)",
  Dashed: "\n---",
  Star: "\n***",
  "Code Block": "`This is a code block.`",
};
